apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello
  namespace: pruebas
spec:
  selector:
      matchLabels:
        app: hello
  replicas: 1
  template:
      metadata:
        labels:
            app: hello
      spec:
        containers:
        - name: hello
          image: vfernandezg/hello:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: hello
  namespace: pruebas
spec:
  selector:
    app: hello
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: LoadBalancer